// <auto-generated />
using System;
using MetroDelivery.Identity.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MetroDelivery.Identity.Migrations
{
    [DbContext(typeof(MetroPickupIdentityDbContext))]
    [Migration("20231001164429_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MetroDelivery.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9afcdfac-1a27-496b-84e5-0c8e5804e40e"),
                            CategoryName = "Food",
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(6596),
                            IsDelete = false
                        },
                        new
                        {
                            Id = new Guid("4078ef19-ba53-481d-9c5a-1c37dfe0e0dc"),
                            CategoryName = "Beverages",
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(6618),
                            IsDelete = false
                        },
                        new
                        {
                            Id = new Guid("b7a3a853-73c6-4f02-913b-9765019e9bd0"),
                            CategoryName = "Bread",
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(6620),
                            IsDelete = false
                        },
                        new
                        {
                            Id = new Guid("175d4c8d-d2f0-441b-85cb-45a1cb0b6756"),
                            CategoryName = "Candy",
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(6622),
                            IsDelete = false
                        },
                        new
                        {
                            Id = new Guid("8908ea98-b421-420b-9634-03ed356bb921"),
                            CategoryName = "Chips",
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(6631),
                            IsDelete = false
                        },
                        new
                        {
                            Id = new Guid("9b2cccb2-f5fa-4358-8265-0fe4f7a52253"),
                            CategoryName = "Cookies",
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(6633),
                            IsDelete = false
                        },
                        new
                        {
                            Id = new Guid("39696f0c-2c8a-480f-b917-141b7da708e4"),
                            CategoryName = "Dairy",
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(6635),
                            IsDelete = false
                        });
                });

            modelBuilder.Entity("MetroDelivery.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f9589c1a-3cbc-4215-bb84-b8fa7d719440"),
                            Address = "da nang",
                            ApplicationUserId = "2C0B43BB-B991-408E-A8F3-2FD3B4A2AB84",
                            Birthday = new DateTime(2002, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(8594),
                            IsDelete = false,
                            Phone = "03030303"
                        },
                        new
                        {
                            Id = new Guid("b9cf3487-3d04-4cbf-85b7-e33360566485"),
                            Address = "hcm",
                            ApplicationUserId = "2198E4CD-3305-49C5-B78A-0B54DD76898F",
                            Birthday = new DateTime(2010, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(8637),
                            IsDelete = false,
                            Phone = "03030303"
                        });
                });

            modelBuilder.Entity("MetroDelivery.Domain.Entities.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("EndTimeService")
                        .HasColumnType("time");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("StartTimeService")
                        .HasColumnType("time");

                    b.Property<Guid>("StoreID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StoreID");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = new Guid("56cba664-cb0a-49c8-a6d6-cbe6a5455ec2"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(6821),
                            EndTimeService = new TimeSpan(0, 10, 0, 0, 0),
                            IsDelete = false,
                            StartTimeService = new TimeSpan(0, 6, 0, 0, 0),
                            StoreID = new Guid("aa2610a8-de94-42b7-b12b-1cf8710e05d8")
                        },
                        new
                        {
                            Id = new Guid("72cb9180-9aba-4b44-ade4-7a3586391f8d"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(6863),
                            EndTimeService = new TimeSpan(0, 15, 0, 0, 0),
                            IsDelete = false,
                            StartTimeService = new TimeSpan(0, 10, 0, 0, 0),
                            StoreID = new Guid("aa2610a8-de94-42b7-b12b-1cf8710e05d8")
                        },
                        new
                        {
                            Id = new Guid("5fcca20e-90d0-49b4-a933-56d044c4f80b"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(6870),
                            EndTimeService = new TimeSpan(0, 23, 0, 0, 0),
                            IsDelete = false,
                            StartTimeService = new TimeSpan(0, 15, 0, 0, 0),
                            StoreID = new Guid("aa2610a8-de94-42b7-b12b-1cf8710e05d8")
                        },
                        new
                        {
                            Id = new Guid("9310e385-5e67-45bf-8af2-58b7d2c7593d"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(6875),
                            EndTimeService = new TimeSpan(0, 10, 0, 0, 0),
                            IsDelete = false,
                            StartTimeService = new TimeSpan(0, 6, 0, 0, 0),
                            StoreID = new Guid("d3599df7-877e-41c7-832d-14850e5c88bd")
                        },
                        new
                        {
                            Id = new Guid("298de718-8200-42f4-ab92-9b43c97c744a"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(6881),
                            EndTimeService = new TimeSpan(0, 15, 0, 0, 0),
                            IsDelete = false,
                            StartTimeService = new TimeSpan(0, 10, 0, 0, 0),
                            StoreID = new Guid("d3599df7-877e-41c7-832d-14850e5c88bd")
                        },
                        new
                        {
                            Id = new Guid("7e2f6320-8b19-4561-b3d2-5f672e01b594"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(6890),
                            EndTimeService = new TimeSpan(0, 23, 0, 0, 0),
                            IsDelete = false,
                            StartTimeService = new TimeSpan(0, 15, 0, 0, 0),
                            StoreID = new Guid("d3599df7-877e-41c7-832d-14850e5c88bd")
                        });
                });

            modelBuilder.Entity("MetroDelivery.Domain.Entities.Menu_Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MenuID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MenuID");

                    b.HasIndex("ProductID");

                    b.ToTable("Menu_Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4f42718b-fdcc-457f-975f-6f90a7149cb3"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(7010),
                            IsDelete = false,
                            MenuID = new Guid("56cba664-cb0a-49c8-a6d6-cbe6a5455ec2"),
                            ProductID = new Guid("45cdf6ed-820f-40df-8e4b-baaad897d8df")
                        },
                        new
                        {
                            Id = new Guid("fad17a59-5593-4f80-abc8-852a7670ea03"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(7015),
                            IsDelete = false,
                            MenuID = new Guid("56cba664-cb0a-49c8-a6d6-cbe6a5455ec2"),
                            ProductID = new Guid("dc38c67e-7b6b-45af-95a9-fc8b0097c2c8")
                        });
                });

            modelBuilder.Entity("MetroDelivery.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderTokenQR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StoreID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.Property<Guid>("TripID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CustomerID");

                    b.HasIndex("StoreID");

                    b.HasIndex("TripID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MetroDelivery.Domain.Entities.OrderDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.Property<int>("quanity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderID");

                    b.HasIndex("ProductID");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("MetroDelivery.Domain.Entities.PaymentMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PaymentMethodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderID");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("MetroDelivery.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<Guid>("StoreID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategoryID");

                    b.HasIndex("StoreID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c19c7202-727c-4721-830d-05f6069dd2f2"),
                            CategoryID = new Guid("175d4c8d-d2f0-441b-85cb-45a1cb0b6756"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(7130),
                            IsDelete = false,
                            Price = 5000.5,
                            ProductDescription = "Kẹo thơm ngon được tạo ra từ các loại đường, được làm nóng và tạo nên hương vị ngọt ngào",
                            ProductName = "Keo bông gòn",
                            Stock = 300,
                            StoreID = new Guid("aa2610a8-de94-42b7-b12b-1cf8710e05d8")
                        },
                        new
                        {
                            Id = new Guid("629aeaa0-8d6c-4275-bdc7-bb03ae53619f"),
                            CategoryID = new Guid("175d4c8d-d2f0-441b-85cb-45a1cb0b6756"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(7136),
                            IsDelete = false,
                            Price = 3000.0,
                            ProductDescription = "Kẹo lạc thơm ngon, giòn tan",
                            ProductName = "Kẹo lạc",
                            Stock = 200,
                            StoreID = new Guid("aa2610a8-de94-42b7-b12b-1cf8710e05d8")
                        },
                        new
                        {
                            Id = new Guid("45cdf6ed-820f-40df-8e4b-baaad897d8df"),
                            CategoryID = new Guid("175d4c8d-d2f0-441b-85cb-45a1cb0b6756"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(7139),
                            IsDelete = false,
                            Price = 3000.0,
                            ProductDescription = "Kẹo lạc thơm ngon, giòn tan",
                            ProductName = "Kẹo chup",
                            Stock = 200,
                            StoreID = new Guid("aa2610a8-de94-42b7-b12b-1cf8710e05d8")
                        },
                        new
                        {
                            Id = new Guid("dc38c67e-7b6b-45af-95a9-fc8b0097c2c8"),
                            CategoryID = new Guid("8908ea98-b421-420b-9634-03ed356bb921"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(7145),
                            IsDelete = false,
                            Price = 10000.0,
                            ProductDescription = "Khoai tây chiên giòn tan",
                            ProductName = "Khoai tây chiên",
                            Stock = 500,
                            StoreID = new Guid("aa2610a8-de94-42b7-b12b-1cf8710e05d8")
                        },
                        new
                        {
                            Id = new Guid("cea11a52-6d68-424c-89a7-d9541b383432"),
                            CategoryID = new Guid("175d4c8d-d2f0-441b-85cb-45a1cb0b6756"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(7149),
                            IsDelete = false,
                            Price = 2500.0,
                            ProductDescription = "Kẹo dẻo mềm, đàn hồi",
                            ProductName = "Kẹo dẻo",
                            Stock = 500,
                            StoreID = new Guid("aa2610a8-de94-42b7-b12b-1cf8710e05d8")
                        },
                        new
                        {
                            Id = new Guid("058e3b19-0714-432e-bb7a-49142bea6b4c"),
                            CategoryID = new Guid("9afcdfac-1a27-496b-84e5-0c8e5804e40e"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(7153),
                            IsDelete = false,
                            Price = 30000.0,
                            ProductDescription = "Cơm gà xé thơm ngon",
                            ProductName = "Cơm gà xé",
                            Stock = 200,
                            StoreID = new Guid("aa2610a8-de94-42b7-b12b-1cf8710e05d8")
                        },
                        new
                        {
                            Id = new Guid("7704418b-6d4c-4127-b7b0-849344433bac"),
                            CategoryID = new Guid("9b2cccb2-f5fa-4358-8265-0fe4f7a52253"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(7156),
                            IsDelete = false,
                            Price = 5000.0,
                            ProductDescription = "Bánh quy giòn tan trong miệng",
                            ProductName = "Bánh quy giòn",
                            Stock = 1000,
                            StoreID = new Guid("aa2610a8-de94-42b7-b12b-1cf8710e05d8")
                        },
                        new
                        {
                            Id = new Guid("0b252747-5e57-4167-b3fd-0f76daf5bb88"),
                            CategoryID = new Guid("175d4c8d-d2f0-441b-85cb-45a1cb0b6756"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(7159),
                            IsDelete = false,
                            Price = 10000.0,
                            ProductDescription = "Kẹo sô cô la ngọt thanh",
                            ProductName = "Kẹo Socola",
                            Stock = 1000,
                            StoreID = new Guid("aa2610a8-de94-42b7-b12b-1cf8710e05d8")
                        },
                        new
                        {
                            Id = new Guid("7d385ca0-7e34-4d97-a8c1-6af6bb08924e"),
                            CategoryID = new Guid("175d4c8d-d2f0-441b-85cb-45a1cb0b6756"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(7164),
                            IsDelete = false,
                            Price = 15000.0,
                            ProductDescription = "Kẹo dâu tây thơm ngon",
                            ProductName = "Kẹo dâu",
                            Stock = 800,
                            StoreID = new Guid("aa2610a8-de94-42b7-b12b-1cf8710e05d8")
                        },
                        new
                        {
                            Id = new Guid("c980e0d7-397d-4900-b3b1-eaff1d8be2b0"),
                            CategoryID = new Guid("9afcdfac-1a27-496b-84e5-0c8e5804e40e"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(7167),
                            IsDelete = false,
                            Price = 50000.0,
                            ProductDescription = "Gà rán giòn tan thơm ngon",
                            ProductName = "Gà rán",
                            Stock = 500,
                            StoreID = new Guid("aa2610a8-de94-42b7-b12b-1cf8710e05d8")
                        },
                        new
                        {
                            Id = new Guid("8681163b-9e5c-40b8-b6c6-ce234b02eab6"),
                            CategoryID = new Guid("9afcdfac-1a27-496b-84e5-0c8e5804e40e"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(7170),
                            IsDelete = false,
                            Price = 65000.0,
                            ProductDescription = "Cá chiên giòn rụm",
                            ProductName = "Cá chiên",
                            Stock = 300,
                            StoreID = new Guid("aa2610a8-de94-42b7-b12b-1cf8710e05d8")
                        },
                        new
                        {
                            Id = new Guid("31301575-70df-45a0-bca5-4bf9a05a7f52"),
                            CategoryID = new Guid("175d4c8d-d2f0-441b-85cb-45a1cb0b6756"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(7238),
                            IsDelete = false,
                            Price = 5000.0,
                            ProductDescription = "Kẹo bạc hà mát lạnh",
                            ProductName = "Kẹo bạc hà",
                            Stock = 1200,
                            StoreID = new Guid("aa2610a8-de94-42b7-b12b-1cf8710e05d8")
                        },
                        new
                        {
                            Id = new Guid("3bc0c06f-d190-45ef-8946-29c35ed79a2b"),
                            CategoryID = new Guid("175d4c8d-d2f0-441b-85cb-45a1cb0b6756"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(7244),
                            IsDelete = false,
                            Price = 2500.0,
                            ProductDescription = "Kẹo mút mềm dẻo",
                            ProductName = "Kẹo mút",
                            Stock = 2000,
                            StoreID = new Guid("aa2610a8-de94-42b7-b12b-1cf8710e05d8")
                        },
                        new
                        {
                            Id = new Guid("9b78ed8c-0341-486e-98b9-620158693e24"),
                            CategoryID = new Guid("9afcdfac-1a27-496b-84e5-0c8e5804e40e"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(7247),
                            IsDelete = false,
                            Price = 80000.0,
                            ProductDescription = "Gà nướng thơm phức",
                            ProductName = "Gà nướng",
                            Stock = 800,
                            StoreID = new Guid("aa2610a8-de94-42b7-b12b-1cf8710e05d8")
                        },
                        new
                        {
                            Id = new Guid("d498e0a5-a236-466d-8958-0bd0115e1bac"),
                            CategoryID = new Guid("9afcdfac-1a27-496b-84e5-0c8e5804e40e"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(7250),
                            IsDelete = false,
                            Price = 25000.0,
                            ProductDescription = "Cơm chiên dương châu thơm ngon",
                            ProductName = "Cơm chiên dương châu",
                            Stock = 1000,
                            StoreID = new Guid("aa2610a8-de94-42b7-b12b-1cf8710e05d8")
                        });
                });

            modelBuilder.Entity("MetroDelivery.Domain.Entities.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("FromLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ea675490-eecd-4308-bb71-61b72a9c979f"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(7604),
                            FromLocation = "Quận 1, Tp.Hcm",
                            IsDelete = false,
                            ToLocation = "Quận 9, Tp.Hcm"
                        },
                        new
                        {
                            Id = new Guid("001a254c-02d4-40e7-a01f-95f393fb41ef"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(7607),
                            FromLocation = "Quận 1, Tp.Hcm",
                            IsDelete = false,
                            ToLocation = "Suối Tiên, Đồng Nai"
                        },
                        new
                        {
                            Id = new Guid("a437b242-55fc-4146-a2b9-8c952b107e3a"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(7609),
                            FromLocation = "Quận 1, Tp.Hcm",
                            IsDelete = false,
                            ToLocation = "Quận Thủ Đức, Tp.Hcm"
                        },
                        new
                        {
                            Id = new Guid("ccc66514-0597-4d43-aaff-0c5d8ee59ffa"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(7611),
                            FromLocation = "Quận 1, Tp.Hcm",
                            IsDelete = false,
                            ToLocation = "Quận Bình Thạnh, Tp.Hcm"
                        },
                        new
                        {
                            Id = new Guid("b9f8f712-92ee-4611-ad55-000a8e1b84c6"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(7615),
                            FromLocation = "Quận 1, Tp.Hcm",
                            IsDelete = false,
                            ToLocation = "Bến xe Miền Đông"
                        });
                });

            modelBuilder.Entity("MetroDelivery.Domain.Entities.Route_Station", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RouteID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StationID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RouteID");

                    b.HasIndex("StationID");

                    b.ToTable("Route_Stations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("50cb67f8-421e-4aec-85ed-7114e763d6c4"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(7447),
                            IsDelete = false,
                            RouteID = new Guid("ea675490-eecd-4308-bb71-61b72a9c979f"),
                            StationID = new Guid("50cb67f8-421e-4aec-85ed-7114e763d6c4")
                        },
                        new
                        {
                            Id = new Guid("1b22bdb7-1688-42fa-8fae-4af92e32df7f"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(7452),
                            IsDelete = false,
                            RouteID = new Guid("ccc66514-0597-4d43-aaff-0c5d8ee59ffa"),
                            StationID = new Guid("50cb67f8-421e-4aec-85ed-7114e763d6c4")
                        },
                        new
                        {
                            Id = new Guid("2ff9d0d9-474c-4466-b9a8-707b730f415c"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(7458),
                            IsDelete = false,
                            RouteID = new Guid("a437b242-55fc-4146-a2b9-8c952b107e3a"),
                            StationID = new Guid("50cb67f8-421e-4aec-85ed-7114e763d6c4")
                        },
                        new
                        {
                            Id = new Guid("ab2099b4-e511-42ff-9e6a-ee71bddcd482"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(7460),
                            IsDelete = false,
                            RouteID = new Guid("001a254c-02d4-40e7-a01f-95f393fb41ef"),
                            StationID = new Guid("50cb67f8-421e-4aec-85ed-7114e763d6c4")
                        },
                        new
                        {
                            Id = new Guid("6a82db5a-23cf-4764-b7d1-ccabce5cc317"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(7463),
                            IsDelete = false,
                            RouteID = new Guid("b9f8f712-92ee-4611-ad55-000a8e1b84c6"),
                            StationID = new Guid("50cb67f8-421e-4aec-85ed-7114e763d6c4")
                        },
                        new
                        {
                            Id = new Guid("5004477e-1446-467d-8157-972185d64290"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(7465),
                            IsDelete = false,
                            RouteID = new Guid("ccc66514-0597-4d43-aaff-0c5d8ee59ffa"),
                            StationID = new Guid("50cb67f8-421e-4aec-85ed-7114e763d6c5")
                        });
                });

            modelBuilder.Entity("MetroDelivery.Domain.Entities.Station", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StoreID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StoreID");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("50cb67f8-421e-4aec-85ed-7114e763d6c4"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(7735),
                            IsDelete = false,
                            StationName = "Ga Metro Bến Thành",
                            StoreID = new Guid("aa2610a8-de94-42b7-b12b-1cf8710e05d8")
                        },
                        new
                        {
                            Id = new Guid("50cb67f8-421e-4aec-85ed-7114e763d6c5"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(7743),
                            IsDelete = false,
                            StationName = "Ga Metro Vincom Bình Thạnh",
                            StoreID = new Guid("aa2610a8-de94-42b7-b12b-1cf8710e05d8")
                        },
                        new
                        {
                            Id = new Guid("50cb67f8-421e-4aec-85ed-7114e763d6c6"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(7746),
                            IsDelete = false,
                            StationName = "Ga Metro Chợ Thủ Đức",
                            StoreID = new Guid("aa2610a8-de94-42b7-b12b-1cf8710e05d8")
                        },
                        new
                        {
                            Id = new Guid("50cb67f8-421e-4aec-85ed-7114e763d6c7"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(7748),
                            IsDelete = false,
                            StationName = "Ga Metro Khu Công Nghệ Cao",
                            StoreID = new Guid("aa2610a8-de94-42b7-b12b-1cf8710e05d8")
                        },
                        new
                        {
                            Id = new Guid("50cb67f8-421e-4aec-85ed-7114e763d6c8"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(7751),
                            IsDelete = false,
                            StationName = "Ga Metro Suối Tiên",
                            StoreID = new Guid("aa2610a8-de94-42b7-b12b-1cf8710e05d8")
                        },
                        new
                        {
                            Id = new Guid("50cb67f8-421e-4aec-85ed-7114e763d6c9"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(7753),
                            IsDelete = false,
                            StationName = "Ga Metro Bến xe Miền Đông",
                            StoreID = new Guid("aa2610a8-de94-42b7-b12b-1cf8710e05d8")
                        });
                });

            modelBuilder.Entity("MetroDelivery.Domain.Entities.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("StoreCloseTime")
                        .HasColumnType("time");

                    b.Property<string>("StoreLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("StoreOpenTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aa2610a8-de94-42b7-b12b-1cf8710e05d8"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(7911),
                            IsDelete = false,
                            StoreCloseTime = new TimeSpan(0, 23, 0, 0, 0),
                            StoreLocation = "Số 2, Đường Lê Lai, Quận 1",
                            StoreName = "Metro PickUp 1",
                            StoreOpenTime = new TimeSpan(0, 6, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("d3599df7-877e-41c7-832d-14850e5c88bd"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(7929),
                            IsDelete = false,
                            StoreCloseTime = new TimeSpan(0, 6, 0, 0, 0),
                            StoreLocation = "Số 3, Vincom, Quận Bình Thạnh",
                            StoreName = "Metro PickUp 2",
                            StoreOpenTime = new TimeSpan(0, 6, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("2f3eee35-1b8e-43af-956f-eacd94eea7cd"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(7935),
                            IsDelete = false,
                            StoreCloseTime = new TimeSpan(0, 6, 0, 0, 0),
                            StoreLocation = "Số 1, Võ Văn Ngân, Thành Phố Thủ Đức",
                            StoreName = "Metro PickUp 3",
                            StoreOpenTime = new TimeSpan(0, 6, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("70c6a937-f285-4495-8407-b20a0c9b10f3"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(7940),
                            IsDelete = false,
                            StoreCloseTime = new TimeSpan(0, 6, 0, 0, 0),
                            StoreLocation = "Khu Công Nghệ Cao Thành Phố Thủ Đức ",
                            StoreName = "Metro PickUp 4",
                            StoreOpenTime = new TimeSpan(0, 6, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("ef443e4b-886c-4c06-8528-51e9cf623867"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(7947),
                            IsDelete = false,
                            StoreCloseTime = new TimeSpan(0, 6, 0, 0, 0),
                            StoreLocation = "Suối tiên",
                            StoreName = "Metro PickUp 5",
                            StoreOpenTime = new TimeSpan(0, 6, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("6507b7db-7255-4274-87a4-6e2dc3d8a3c4"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(7952),
                            IsDelete = false,
                            StoreCloseTime = new TimeSpan(0, 6, 0, 0, 0),
                            StoreLocation = "Bến Xe Miền Đông",
                            StoreName = "Metro PickUp 6",
                            StoreOpenTime = new TimeSpan(0, 6, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("MetroDelivery.Domain.Entities.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TripEndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TripName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TripStartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Trips");

                    b.HasData(
                        new
                        {
                            Id = new Guid("823ad122-7b51-4dab-9d37-b0f238d4a2ff"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(8221),
                            IsDelete = false,
                            TripEndTime = new DateTime(2023, 7, 17, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            TripName = "Camping Trip",
                            TripStartTime = new DateTime(2023, 7, 15, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("9c2ab923-4c57-44d7-9c1a-b44c0d3e6b00"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(8317),
                            IsDelete = false,
                            TripEndTime = new DateTime(2023, 5, 25, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            TripName = "Road Trip",
                            TripStartTime = new DateTime(2023, 5, 20, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("02859382-d88c-4e69-8c47-b8e0456677d5"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(8328),
                            IsDelete = false,
                            TripEndTime = new DateTime(2023, 9, 15, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            TripName = "Cruise Vacation",
                            TripStartTime = new DateTime(2023, 9, 10, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("27421cac-1da7-4df8-9928-7fb636ca42aa"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(8337),
                            IsDelete = false,
                            TripEndTime = new DateTime(2023, 11, 14, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            TripName = "Hiking Adventure",
                            TripStartTime = new DateTime(2023, 11, 12, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("5b30c4e9-31ab-456c-b212-dc6b2ba9a3e7"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(8347),
                            IsDelete = false,
                            TripEndTime = new DateTime(2023, 12, 23, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            TripName = "Ski Getaway",
                            TripStartTime = new DateTime(2023, 12, 20, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("9b4d232c-0fda-4ec0-beed-ecd649ee9c52"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(8356),
                            IsDelete = false,
                            TripEndTime = new DateTime(2023, 8, 18, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            TripName = "Tropical Vacation",
                            TripStartTime = new DateTime(2023, 8, 13, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("bf736039-33e9-466f-ac4e-78c89f3317e6"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(8366),
                            IsDelete = false,
                            TripEndTime = new DateTime(2023, 7, 6, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            TripName = "Amusement Park Fun",
                            TripStartTime = new DateTime(2023, 7, 4, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("8a2ba7d5-7019-49c6-a47d-ab0a072e7932"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(8379),
                            IsDelete = false,
                            TripEndTime = new DateTime(2023, 10, 3, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            TripName = "African Safari",
                            TripStartTime = new DateTime(2023, 9, 28, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d9852f0d-e836-4a6e-94f4-d229b297933d"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(8389),
                            IsDelete = false,
                            TripEndTime = new DateTime(2023, 5, 8, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            TripName = "Botanical Gardens Tour",
                            TripStartTime = new DateTime(2023, 5, 6, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MetroDelivery.Domain.Entities.Trip_Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RouteID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TripID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RouteID");

                    b.HasIndex("TripID");

                    b.ToTable("Trip_Routes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c5f64589-89de-4888-8cc6-0a2dffde7af6"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(8089),
                            IsDelete = false,
                            RouteID = new Guid("001a254c-02d4-40e7-a01f-95f393fb41ef"),
                            TripID = new Guid("823ad122-7b51-4dab-9d37-b0f238d4a2ff")
                        },
                        new
                        {
                            Id = new Guid("a67985f2-53c9-4942-bf3e-85f6a66a1f59"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(8093),
                            IsDelete = false,
                            RouteID = new Guid("a437b242-55fc-4146-a2b9-8c952b107e3a"),
                            TripID = new Guid("02859382-d88c-4e69-8c47-b8e0456677d5")
                        },
                        new
                        {
                            Id = new Guid("ca2c4fc5-cb43-4811-8390-112aebbb2eb4"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(8096),
                            IsDelete = false,
                            RouteID = new Guid("ccc66514-0597-4d43-aaff-0c5d8ee59ffa"),
                            TripID = new Guid("27421cac-1da7-4df8-9928-7fb636ca42aa")
                        },
                        new
                        {
                            Id = new Guid("de514889-2bce-4958-8377-513cc537a938"),
                            Created = new DateTime(2023, 10, 1, 23, 44, 29, 295, DateTimeKind.Local).AddTicks(8101),
                            IsDelete = false,
                            RouteID = new Guid("b9f8f712-92ee-4611-ad55-000a8e1b84c6"),
                            TripID = new Guid("5b30c4e9-31ab-456c-b212-dc6b2ba9a3e7")
                        });
                });

            modelBuilder.Entity("MetroDelivery.Domain.Entities.WithDraw", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("Balance")
                        .HasColumnType("float");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerID");

                    b.ToTable("WithDraws");
                });

            modelBuilder.Entity("MetroDelivery.Domain.IdentityModels.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "2198E4CD-3305-49C5-B78A-0B54DD76898F",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2c4c19b1-4262-463c-ba2d-45f26f3dda78",
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Nhan",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEKbIlyfp7NvxUPshFKhRaqJ7yaGZ+SGV0d9LfhvP1WxOKwqV6lhImzvb3TW1oI0Qew==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e8e039cd-b753-4dcb-85f7-97f2379bc72b",
                            TwoFactorEnabled = false,
                            UserName = "admin@gmail.com"
                        },
                        new
                        {
                            Id = "E6DE8827-B7C2-46E9-9227-66E6ECE676A8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "709ce706-071f-41bd-9923-cae713772eaa",
                            Email = "enduser@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Vi",
                            LastName = "EndUser",
                            LockoutEnabled = false,
                            NormalizedEmail = "ENDUSER@GMAIL.COM",
                            NormalizedUserName = "ENDUSER@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAECCZoAgEZMawE9sRNRd1ral5EAsGRlcmtm4sej8r1BNJ3VTz8kywE/Q9s9zMm7NPog==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "41523b08-acf0-4863-91f9-7895e8843642",
                            TwoFactorEnabled = false,
                            UserName = "enduser@gmail.com"
                        },
                        new
                        {
                            Id = "2C0B43BB-B991-408E-A8F3-2FD3B4A2AB84",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4e28a76c-ee26-44dc-a7e2-107755f50c50",
                            Email = "staff@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Vi",
                            LastName = "Staff",
                            LockoutEnabled = false,
                            NormalizedEmail = "STAFF@GMAIL.COM",
                            NormalizedUserName = "STAFF@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAENhKt0pH8xeiHFiXa81a1z5WkxyKP2rAZVtew8wfuJz6toGvU+QmXswlHCs93Kn4Ug==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a5d3cbcc-e2c0-4d9c-9688-be00cf3894e8",
                            TwoFactorEnabled = false,
                            UserName = "staff@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "CF531396-C1CD-427B-9D17-0383B7675394",
                            ConcurrencyStamp = "e347eaf0-4ec6-41ab-9a48-b04a0495ffb0",
                            Name = "EndUser",
                            NormalizedName = "EndUser"
                        },
                        new
                        {
                            Id = "AF5EB4AC-219A-4BC1-99FE-8C23876536EA",
                            ConcurrencyStamp = "d4b116c1-7536-478e-adcd-4e06c216d09b",
                            Name = "Admin",
                            NormalizedName = "Admin"
                        },
                        new
                        {
                            Id = "647D9649-F5A2-4F24-808F-6FC326EC2AA3",
                            ConcurrencyStamp = "80dfe0aa-add4-4d42-9785-c87101296ce4",
                            Name = "Staff",
                            NormalizedName = "Staff"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "2C0B43BB-B991-408E-A8F3-2FD3B4A2AB84",
                            RoleId = "647D9649-F5A2-4F24-808F-6FC326EC2AA3"
                        },
                        new
                        {
                            UserId = "E6DE8827-B7C2-46E9-9227-66E6ECE676A8",
                            RoleId = "CF531396-C1CD-427B-9D17-0383B7675394"
                        },
                        new
                        {
                            UserId = "2198E4CD-3305-49C5-B78A-0B54DD76898F",
                            RoleId = "AF5EB4AC-219A-4BC1-99FE-8C23876536EA"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MetroDelivery.Domain.Entities.Customer", b =>
                {
                    b.HasOne("MetroDelivery.Domain.IdentityModels.ApplicationUser", "ApplicationUser")
                        .WithOne("Customer")
                        .HasForeignKey("MetroDelivery.Domain.Entities.Customer", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("MetroDelivery.Domain.Entities.Menu", b =>
                {
                    b.HasOne("MetroDelivery.Domain.Entities.Store", "Store")
                        .WithMany("Menus")
                        .HasForeignKey("StoreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("MetroDelivery.Domain.Entities.Menu_Product", b =>
                {
                    b.HasOne("MetroDelivery.Domain.Entities.Menu", "Menu")
                        .WithMany("Menu_Products")
                        .HasForeignKey("MenuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetroDelivery.Domain.Entities.Product", "Products")
                        .WithMany("Menu_Products")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("MetroDelivery.Domain.Entities.Order", b =>
                {
                    b.HasOne("MetroDelivery.Domain.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetroDelivery.Domain.Entities.Store", "Store")
                        .WithMany("Orders")
                        .HasForeignKey("StoreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetroDelivery.Domain.Entities.Trip", "Trip")
                        .WithMany("Order")
                        .HasForeignKey("TripID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Store");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("MetroDelivery.Domain.Entities.OrderDetail", b =>
                {
                    b.HasOne("MetroDelivery.Domain.Entities.Order", "Order")
                        .WithMany("OrderDetail")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetroDelivery.Domain.Entities.Product", "Products")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("MetroDelivery.Domain.Entities.PaymentMethod", b =>
                {
                    b.HasOne("MetroDelivery.Domain.Entities.Order", "Order")
                        .WithMany("PaymentMethods")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("MetroDelivery.Domain.Entities.Product", b =>
                {
                    b.HasOne("MetroDelivery.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetroDelivery.Domain.Entities.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("MetroDelivery.Domain.Entities.Route_Station", b =>
                {
                    b.HasOne("MetroDelivery.Domain.Entities.Route", "Route")
                        .WithMany("Route_Stations")
                        .HasForeignKey("RouteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetroDelivery.Domain.Entities.Station", "Station")
                        .WithMany("Route_Stations")
                        .HasForeignKey("StationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("MetroDelivery.Domain.Entities.Station", b =>
                {
                    b.HasOne("MetroDelivery.Domain.Entities.Store", "Store")
                        .WithMany("Stations")
                        .HasForeignKey("StoreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("MetroDelivery.Domain.Entities.Trip_Route", b =>
                {
                    b.HasOne("MetroDelivery.Domain.Entities.Route", "Route")
                        .WithMany("Trip_Routes")
                        .HasForeignKey("RouteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetroDelivery.Domain.Entities.Trip", "Trip")
                        .WithMany("Trip_Routes")
                        .HasForeignKey("TripID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("MetroDelivery.Domain.Entities.WithDraw", b =>
                {
                    b.HasOne("MetroDelivery.Domain.Entities.Customer", "Customer")
                        .WithMany("WithDraws")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MetroDelivery.Domain.IdentityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MetroDelivery.Domain.IdentityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetroDelivery.Domain.IdentityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MetroDelivery.Domain.IdentityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MetroDelivery.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("WithDraws");
                });

            modelBuilder.Entity("MetroDelivery.Domain.Entities.Menu", b =>
                {
                    b.Navigation("Menu_Products");
                });

            modelBuilder.Entity("MetroDelivery.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderDetail");

                    b.Navigation("PaymentMethods");
                });

            modelBuilder.Entity("MetroDelivery.Domain.Entities.Product", b =>
                {
                    b.Navigation("Menu_Products");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("MetroDelivery.Domain.Entities.Route", b =>
                {
                    b.Navigation("Route_Stations");

                    b.Navigation("Trip_Routes");
                });

            modelBuilder.Entity("MetroDelivery.Domain.Entities.Station", b =>
                {
                    b.Navigation("Route_Stations");
                });

            modelBuilder.Entity("MetroDelivery.Domain.Entities.Store", b =>
                {
                    b.Navigation("Menus");

                    b.Navigation("Orders");

                    b.Navigation("Stations");
                });

            modelBuilder.Entity("MetroDelivery.Domain.Entities.Trip", b =>
                {
                    b.Navigation("Order");

                    b.Navigation("Trip_Routes");
                });

            modelBuilder.Entity("MetroDelivery.Domain.IdentityModels.ApplicationUser", b =>
                {
                    b.Navigation("Customer")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
